### ISSUE TITLE
Handshake not received: publisherEndpoint

### ISSUE THREAD

**Issue by mullachv** [brooklyn-omniheurists/evasion#22]
I get the following error message, when sending "P" and "W" commands to publisherEndpoint:
javax.websocket.DeploymentException: Handshake response not received.
    at org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:694)
    at org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:712)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:866)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
    at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:511)
    at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:355)
#     at evasion.App.main(App.java:60)

code:
            client.connectToServer(publisher, cec, new URI(publisherEndpoint));
            messageLatch.await(100, TimeUnit.SECONDS);

**Comment by brooklyn-omniheurists** [comment]
I'm not sure what's causing this, but we'll take a look at the java again

**Comment by brooklyn-omniheurists** [comment]
Is the server.js running? This is only a client after all.

**Comment by brooklyn-omniheurists** [comment]
This looked solved, unknown why.
