### ISSUE TITLE
Error running node server.js 

### ISSUE THREAD

**Issue by mullachv** [brooklyn-omniheurists/evasion#3]
$pwd
/Users/vmullachery/workspace/brooklyn-omniheurists/evasion

Vikrams-MBP:evasion vmullachery$ ls
README.md   evasion     readme      server.js   test.html

Vikrams-MBP:evasion vmullachery$ node server.js 
/Users/vmullachery/workspace/brooklyn-omniheurists/evasion/server.js:491
});
 ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
Vikrams-MBP:evasion vmullachery$

**Comment by mullachv** [comment]
$ node -v
v4.2.1

**Comment by KshitizSethia** [comment]
Anyone found a resolution to this?

Apparently, the file is only 490 lines and the error is on line #491.

**Comment by mutaphore** [comment]
I'm having the same issue, can't run the server...

**Comment by mayanks43** [comment]
**Remove the opening paren. at the end of the [line](https://github.com/brooklyn-omniheurists/evasion/blob/master/server.js#L338)**
Server doesn't crash after this but haven't been able to try the java client. (Maybe that works?)

js client crashes server after running first command on test.html.

The error:
New message:
process
sendMove

/home/marcus/heuristic-problem-solving/Evasion/evasion/server.js:207
            moves.splice(0,1);
            ^
ReferenceError: moves is not defined
    at sendMove (/home/marcus/heuristic-problem-solving/Evasion/evasion/server.js:207:13)
    at WebSocketConnection.<anonymous> (/home/marcus/heuristic-problem-solving/Evasion/evasion/server.js:82:13)
    at WebSocketConnection.EventEmitter.emit (events.js:95:17)
    at WebSocketConnection.processFrame (/home/marcus/heuristic-problem-solving/Evasion/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /home/marcus/heuristic-problem-solving/Evasion/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at process._tickCallback (node.js:415:13)

UPDATE:
To fix this error change [this](https://github.com/brooklyn-omniheurists/evasion/blob/master/server.js#L207) line to hMoves.splice(0,1);

UPDATE2:
Something's happening on the server side when I send commands via test.html but can't tell what's going on due to no UI.

**Comment by brooklyn-omniheurists** [comment]
Please pull updated code. All typos have been removed.

Please open console and view printouts to get an understanding of format. I will update documentation for api. Thanks.
