### ISSUE TITLE
unable to build Vertical wall

### ISSUE THREAD

**Issue by KshitizSethia** [brooklyn-omniheurists/evasion#31]
Hi,

This is the json I'm passing from hunter to build vertical wall: 
{"command":"B","wall":{"direction":"V"}}

When server gets this message, it gives the following error:

C:\Cloud\workspace\HeuristicProblemSolving\Evasion\evasion_arch\server.js:344
  return [oldPosition[0] + cardinalDirection[0], oldPosition[1] + cardinalDirection[1]];
                                            ^

TypeError: Cannot read property '0' of undefined
    at move (C:\Cloud\workspace\HeuristicProblemSolving\Evasion\evasion_arch\server.js:344:45)
    at isWallIntersectingHunter (C:\Cloud\workspace\HeuristicProblemSolving\Evasion\evasion_arch\server.js:517:19)
    at isValidWall (C:\Cloud\workspace\HeuristicProblemSolving\Evasion\evasion_arch\server.js:586:21)
    at Object.processHunter [as fun](C:CloudworkspaceHeuristicProblemSolvingEvasionevasion_archserver.js:201:21)
    at sendMove (C:\Cloud\workspace\HeuristicProblemSolving\Evasion\evasion_arch\server.js:303:23)
    at WebSocketConnection.<anonymous> (C:\Cloud\workspace\HeuristicProblemSolving\Evasion\evasion_arch\server.js:135:13)
    at emitOne (events.js:77:13)
    at WebSocketConnection.emit (events.js:169:7)
    at WebSocketConnection.processFrame (C:\Cloud\workspace\HeuristicProblemSolving\Evasion\evasion_arch\node_modules\websocket\l
    at C:\Cloud\workspace\HeuristicProblemSolving\Evasion\evasion_arch\node_modules\websocket\lib\WebSocketConnection.js:321:40

**Comment by KshitizSethia** [comment]
Sorry, had to update the server code
